### ISSUE TITLE
Gauges are still present

### ISSUE THREAD

**Issue by drenda** [JFXtras/jfxtras#10]
Hi,
gauges components are still present in 8.0-r1 release? I can't figure out how to create a simple gauge as this: http://harmoniccode.blogspot.it/2012/09/jfxtras-simplegauge.html

Thanks

**Comment by tbee** [comment]
No. Porting them to JFX8 required a lot of changes to the source code, and Gerrit decided not to. Sorry.

Tom

**Comment by drenda** [comment]
Ok, thanks for your reply!
