### ISSUE TITLE
How to get month and year view ?

### ISSUE THREAD

**Issue by bnlambert** [JFXtras/jfxtras#100]
Hi,
After testing jfxtras-icalendaragenda and jfxtras-agenda, the view does not present me the option to show the Monthly yearly view.
I only see a complete week in the default view.
 I also have a couple of worries such as
- Loading initial appointments into jfxtras-icalendaragenda and saving create appointments into database
- Intellij could not resolve `actionCallback()` of `Agenda`  instance and `getDescription() `of `appointment` (jfxtras-agenda, 8.0-r6)

If there are any resources on how to use these tools or a getting started tutorial, please share.
Thanks

**Comment by tbee** [comment]
The year and month view do not exist, they still need to be programmed.
Agenda has a collection (appointments) and a callback, so the content can be finetuned to the timeframe that is shown, I do not know about icalendaagenda, maybe @daviddbal can comment on that. Agenda has Javadoc explain how to use it (http://jfxtras.org/doc/8.0/jfxtras-agenda/jfxtras/scene/control/agenda/Agenda.html).

JFXtras compiles without problems in the nightly builds, so it must be a project configuration issue.

**Comment by bnlambert** [comment]
Thank you very much for your response.
