### ISSUE TITLE
LocalDateTimeTextField  disable editing

### ISSUE THREAD

**Issue by moctavianro** [JFXtras/jfxtras#103]
Hello
How can i set a string date formatter in fxml layout?
How can i make the field uneditable but keeo picker on?
Can i set min and max values for it(disable the other dates)?

Thanks!

**Comment by tbee** [comment]
Sorry for the late response, my paid job is doing an end-of-year sprint.

1) dateFormat="yyyy-MM-dd HH:mm:ss" dateFormats="yyyy-MM-dd, yyyy-MM, yyyy"
2) no you can't, why do you want that? (If it is a good use case...)
3) no you can't at the moment, but I can see why that would make sense.

**Comment by tbee** [comment]
3) You could use the CalendarRangeCallback and the disabledCalendars collection to disable all dates in a given month (or partial months when the min or max is reached).
