### ISSUE TITLE
Error setting calendar for CalendarPicker

### ISSUE THREAD

**Issue by moctavianro** [JFXtras/jfxtras#106]
If i set a UTC Calendar set to 0 hours, minutes and seconds to CalendarPicker, the clock will start from 2 instead 0.

**Comment by tbee** [comment]
Show me some code. :-)

**Comment by moctavianro** [comment]
Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"), Locale.US);
calendar.setTimeInMillis(DateTimeDialog.getInstance().getTimeToSet());
mCalendarPicker.setCalendar(calendar);

**Comment by moctavianro** [comment]
![capture](https://user-images.githubusercontent.com/6254454/50512303-02d0f200-0a9a-11e9-927f-d9925b562d60.JPG)
![capture2](https://user-images.githubusercontent.com/6254454/50512326-154b2b80-0a9a-11e9-8d7d-5ae2fa7256bf.JPG)

**Comment by moctavianro** [comment]
thanks 4 help dude

**Comment by tbee** [comment]
You are setting a time in the calendar in the second line, no idea what value that is.

But, CalendarPicker is not doing anything with time zones, it uses merely a locale to get the day names right. It just renders the day, month, year, hour, minute, seconds that are in the calendar. Very curious what this line inserted before the setCalendar gives as a result:

System.out.println(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").format(calendar.getTime()));

**Comment by moctavianro** [comment]
as u can see in the photos above, the clock starts from 2 and ends to 1:59. That seems a bug to me since it must start from 0 and end to 23:59

**Comment by tbee** [comment]
ohhhh, I see!

**Comment by moctavianro** [comment]
It happens when i switch the calendar from default to UTC and set it to CalendarPicker.

**Comment by tbee** [comment]
Indeed. Interesting. I can reproduce it now.

**Comment by moctavianro** [comment]
so when i should expect a patch? :))

**Comment by tbee** [comment]
This is open source, so never :-) But I am looking into it now

**Comment by tbee** [comment]
So the cause is in calendar, but I have to think about why. If you execute this code:

```
	Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"), Locale.US);
	System.out.println("H1=" + calendar.get(Calendar.HOUR_OF_DAY) + " / " + new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").format(calendar.getTime()));
	Calendar calendar2 = Calendar.getInstance();
	System.out.println("H2=" + calendar2.get(Calendar.HOUR_OF_DAY) + " / " + new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").format(calendar2.getTime()));

```
I get this output (its just after noon here):
```
	H1=11 / 2018-12-28T12:14:45.468
	H2=12 / 2018-12-28T12:14:45.476
```

What you see if that they format into the same time (12 o'clock), but if you query for the 24-hour value, they differ.

**Comment by moctavianro** [comment]
that s strange indeed. I figured a workaround for me, i get the default time in millis then i extract the timezone raw offset, It works.

**Comment by tbee** [comment]
The formatter uses Date, which is not timezone aware, and thus always renders in the current timezone. The hour of day returns the value in the current timezone. Have to thing about how to solve this best, because date and time picking is done timezone unaware.

**Comment by tbee** [comment]
I think I have fixed it, but the release needs to pass all tests first. It is a fairly large change.

**Comment by moctavianro** [comment]
i see

**Comment by tbee** [comment]
I assume you're still using Java 8? Give 8-r7-SNAPSHOT a try please
