### ISSUE TITLE
JFxtras UI bug when try to switch skin into day view and week view

### ISSUE THREAD

**Issue by jachane99** [JFXtras/jfxtras#109]
this is the default calendar view
![image](https://user-images.githubusercontent.com/43421733/55703629-20223000-59a8-11e9-8d39-d9abb4a1c540.png)
However, when I tried to change to dayView by setting skin to dayView
![image](https://user-images.githubusercontent.com/43421733/55703678-3a5c0e00-59a8-11e9-84d5-9d4e8c0d86a6.png)
the numbers are overlapping for the dayView
Same with when I tried to get next week calendar in week view, all the numbers are overlapping.
![image](https://user-images.githubusercontent.com/43421733/55703728-66778f00-59a8-11e9-8be3-d21cb581b409.png)

**Comment by tbee** [comment]
I'll take a look asap

**Comment by jachane99** [comment]
I got it fixed by some work around. Thank you though

**Comment by tbee** [comment]
I would like to know how. :-)
