### ISSUE TITLE
Provide manifest headers to use JFXtras in OSGi environment

### ISSUE THREAD

**Issue by n-e-g** [JFXtras/jfxtras#11]
The OSGi headers does not affect regular, non-OSGi based build, while allows off-the-shelf  use in OSGi environments. Gradle build system provides plugins for generation of OSGi headers thus the only concern would be to check whether all resource loading uses proper classloader.

**Comment by tbee** [comment]
It seems not very many are using OSGi - personally I've look into it a while back but found it complex - and probably are waiting for a more friendly technique, possibly JBoss modules or Jigsaw. So I'm not inclined to invest time in learning to setup OSGi. If someone with knowledge was to make a PR, it would be included. If not, this change request (or improvement) will probably be closed somewhere in the future.

**Comment by tbee** [comment]
Closed because of inactivity
