### ISSUE TITLE
Broken versioning in Maven Central

### ISSUE THREAD

**Issue by matozoid** [JFXtras/jfxtras#113]
Hi!

Check out https://mvnrepository.com/artifact/org.jfxtras/jfxtras-test-support/10.0-r1

testfx-core has version "testfxVersion". That sounds like a placeholder to me, and it doesn't work when using it from Maven.

**Comment by tbee** [comment]
Please switch to the 11 release. The migration to JPMS has caused 10 to be halfbaked.
