### ISSUE TITLE
DateTimePicker in Vbox with Hgrow not working

### ISSUE THREAD

**Issue by siemlohuis** [JFXtras/jfxtras#119]
I am making a layout that looks like this:
![Screenshot](https://user-images.githubusercontent.com/29313267/80991150-e2f0d180-8e37-11ea-9fb3-0592a4f6a243.png)

But the LocalDateTimeTextField isn't ligned up with the rest of my layout (Smaller then the textfields) because the Hgrow on the VBox'es (Which would make them even sized) don't work with the LocalDateTimeTextField.

The FXML file:
[Fxml.zip](https://github.com/JFXtras/jfxtras/files/4575982/Fxml.zip)

How can I fix this?
Thanks for helping!

**Comment by tbee** [comment]
I'll take a look. What version of JFXtras are you using?

**Comment by tbee** [comment]
Ahm. If you want to align different controls in a grid, nested VBox and HBox is not the way to go. You really should be using a grid layout like MigLayout.
https://github.com/mikaelgrev/miglayout/blob/master/javafx/src/test/resources/MigPaneTest8.xml

**Comment by siemlohuis** [comment]
@tbee Thanks for helping! I got it working with a Gridpane
