### ISSUE TITLE
how to use JFxtras with Scenebuilder on Netbeans 8.2?

### ISSUE THREAD

**Issue by AdemYoussef** [JFXtras/jfxtras#126]
I m a newbie to scenebuilder and JavaFX , all I know is how to configure scenebuilder on Netbeans to use it hehe XD

I m working on a school project and I liked the very useful controls that JFxtrats offers and I want to use them ( i m planing to use ICalendarAgenda )

but I have no idea how to even import or install or whatever ... to make JFxtras working on my ide ( Netbeans 8.2 ) can you please help me?

will be very appreciated!!

PS: Operating System is Windows 10

**Comment by tbee** [comment]
I think we've discussed this already on stackoverflow, if I'm not mistaken. 

Never the less, learning to use scenebuilder, JavaFX and supporting libraries is not a JFXtras issue. You can just download JFXtras and use the controls like any other JavaFX control.
