### ISSUE TITLE
Agenda with specific hour range

### ISSUE THREAD

**Issue by ASchmidt84** [JFXtras/jfxtras#136]
Hello,
i am using agenda. But I dont need all the hours. I need only times like 8 - 18 or 6 - 18.
Is their a way to change the hour display?

Thank you a lot

**Comment by tbee** [comment]
Unfortunately not. The current implementation assumes 0 is midnight and full height is 24 hours.  It is not that dramatically difficult to add, mostly a matter of offsets, but probably in a lot of places.

**Comment by ASchmidt84** [comment]
I am looking a few hours. So really simple isn´t it. Their are a few very good helpers. But too often private. My question at this position TimeScala24Hour.class seemes to be the "problem".
```
private void addTimeScale() {
		
		// draw hours
		for (int lHour = 0; lHour < 24; lHour++)
		{
			// hour line
			{
				Line l = new Line(0,10,100,10);
				l.setId("hourLine" + lHour);
				l.getStyleClass().add("HourLine");
				l.startXProperty().set(0.0);
				l.startYProperty().bind( NodeUtil.snapXY(layoutHelp.hourHeighProperty.multiply(lHour)) );
				l.endXProperty().bind( NodeUtil.snapXY(pane.widthProperty()));
				l.endYProperty().bind( NodeUtil.snapXY(l.startYProperty()));
				getChildren().add(l);
			}
			// half hour line
			{
				Line l = new Line(0,10,100,10);
				l.setId("halfHourLine" + lHour);
				l.getStyleClass().add("HalfHourLine");
				l.startXProperty().bind( NodeUtil.snapXY(layoutHelp.timeWidthProperty));
				l.endXProperty().bind( NodeUtil.snapXY(pane.widthProperty()));
				l.startYProperty().bind( NodeUtil.snapXY(layoutHelp.hourHeighProperty.multiply(lHour + 0.5)));
				l.endYProperty().bind( NodeUtil.snapXY(l.startYProperty()));
				getChildren().add(l);
			}
			// hour text
			{
				Text t = new Text(lHour + ":00");
				t.xProperty().bind(layoutHelp.timeWidthProperty.subtract(t.getBoundsInParent().getWidth()).subtract(layoutHelp.timeColumnWhitespaceProperty.get() / 2));
				t.yProperty().bind(layoutHelp.hourHeighProperty.multiply(lHour));
				t.setTranslateY(t.getBoundsInParent().getHeight()); // move it under the line
				t.getStyleClass().add("HourLabel");
				t.setFontSmoothingType(FontSmoothingType.LCD);
				getChildren().add(t);
			}
		}

	}
```
The for loop takes hardcoded 0 and 24. Maybe it would be better to change that a start and end hour variable with default values. So everyone can choose. No one has a 24 hour day 7 days. And the hour variables, as long the length of a week could be managed by an property/observable.

**Comment by tbee** [comment]
Yes, or define it in the CSS. But there are many more places where this 24h assumption present; DayPane for example.
