### ISSUE TITLE
CSS Problem with CalendarTextField

### ISSUE THREAD

**Issue by simware** [JFXtras/jfxtras#14]
When using the CalendarTextField the following exception is thrown:

SEVERE: The -fx-skin property has not been defined in CSS for ListSpinner[id=yearListSpinner, styleClass=ListSpinner] and createDefaultSkin() returned null.
Oct 09, 2014 4:48:05 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Oct 09, 2014 4:48:05 PM javafx.scene.CssStyleHelper calculateValue

Code examples FXML:
<AnchorPane fx:id="rootPane" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="446.0" prefWidth="546.0" xmlns:fx="http://javafx.com/fxml/1" xmlns="http://javafx.com/javafx/2.2" fx:controller="com.simware.CalendarController">
  <children>
    <VBox id="VBox" alignment="CENTER" layoutX="22.0" layoutY="0.0" spacing="5.0">
      <children>  
        <CalendarTextField fx:id="datePickerStart"
                    prefWidth="150.0" />
      </children>
    </VBox>
  </children>
</AnchorPane>

Code example JAVA:
    @FXML private CalendarTextField datePickerStart;

```
@Override
public void initialize(URL arg0, ResourceBundle arg1) {
    datePickerStart.setDateFormat(SimpleDateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM,
            Locale.getDefault()));
    Calendar calendar = Calendar.getInstance();
    datePickerStart.setCalendar(calendar);

}
```

**Comment by tbee** [comment]
Hmmm, what Java version are you running against?

**Comment by simware** [comment]
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

On Thursday, October 9, 2014 4:58 PM, Tom Eugelink notifications@github.com wrote:

Hmmm, what Java version are you running against?

**Comment by simware** [comment]
Not sure that I answered, sorry for my confusion!

java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

On Thursday, October 9, 2014 4:58 PM, Tom Eugelink notifications@github.com wrote:

Hmmm, what Java version are you running against?

**Comment by tbee** [comment]
And what version of JFXtras?

**Comment by simware** [comment]
8.0-r2 and 8.0-r1

On Monday, October 13, 2014 8:09 AM, Tom Eugelink notifications@github.com wrote:

And what version of JFXtras?

**Comment by tbee** [comment]
Please give 8.0-r3-SNAPSHOT a try. As per (changed) convention I've stopped specifying the default skin in the css.

**Comment by simware** [comment]
Tom,

Same problem with the slight difference that the text box now dose not disappears when clicking on the icon.

A few lines from the CSS problems...

Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-shadow-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.ListSpinner' in stylesheet jar:file:/Users/simon/.m2/repository/org/jfxtras/jfxtras-controls/8.0-r3-SNAPSHOT/jfxtras-controls-8.0-r3-SNAPSHOT.jar!/jfxtras/internal/scene/control/ListSpinner.css
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '_.label' in stylesheet jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '_.label' in stylesheet jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-mark-color' while resolving lookups for '-fx-background-color' from rule '_.ListSpinner _.idle' in stylesheet jar:file:/Users/simon/.m2/repository/org/jfxtras/jfxtras-controls/8.0-r3-SNAPSHOT/jfxtras-controls-8.0-r3-SNAPSHOT.jar!/jfxtras/internal/scene/control/ListSpinner.css
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-mark-color' while resolving lookups for '-fx-background-color' from rule '_.ListSpinner _.idle' in stylesheet jar:file:/Users/simon/.m2/repository/org/jfxtras/jfxtras-controls/8.0-r3-SNAPSHOT/jfxtras-controls-8.0-r3-SNAPSHOT.jar!/jfxtras/internal/scene/control/ListSpinner.css
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-shadow-highlight-color' while resolving lookups for '-fx-background-color' from rule '_.ListSpinner' in stylesheet jar:file:/Users/simon/.m2/repository/org/jfxtras/jfxtras-controls/8.0-r3-SNAPSHOT/jfxtras-controls-8.0-r3-SNAPSHOT.jar!/jfxtras/internal/scene/control/ListSpinner.css
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Oct 14, 2014 2:02:50 PM javafx.scene.CssStyleHelper calculateValue

On Monday, October 13, 2014 11:45 AM, Tom Eugelink notifications@github.com wrote:

Please give 8.0-r3-SNAPSHOT a try. As per (changed) convention I've stopped specifying the default skin in the css.

**Comment by tbee** [comment]
These CSS warnings are a JavaFX problem and are not causing any problems AFAIK, something is not working with the resolution of the aliases.

Can you provide me with a simple example?

**Comment by simware** [comment]
Attached is a example.

On Tuesday, October 14, 2014 2:40 PM, Tom Eugelink notifications@github.com wrote:

These CSS warnings are a JavaFX problem and are not causing any problems AFAIK, something is not working with the resolution of the aliases.
Can you provide me with a simple example?

**Comment by tbee** [comment]
Thanks, I'll take a look. FYI: right now there is an active issue about CSS in 8u40 in JavaFX.

https://javafx-jira.kenai.com/browse/RT-38950

I'm curious what will be the outcome there and if it will require me to refactor the CSS involving the controls.

**Comment by tbee** [comment]
I wanted to take a look, but there is no attachement. You could send it to me directly; tbee@tbee.org.

Tom

**Comment by tbee** [comment]
The warnings are a JavaFX problem and should disappear in u40. The actual issue here is fixed AFAIK.
