### ISSUE TITLE
ListSpinner arrow direction

### ISSUE THREAD

**Issue by kevincoghlan** [JFXtras/jfxtras#15]
EDIT: This issue can be disregarded. Initially, I could not find the support for up/down ListSpinners which seemed to exist in past JavaFX 2.2 versions of Jfxtras.

However, after closer examination of the current Jfxtras APIs, I found the support that I was seeking in the ListSpinnerSkin class.

**Comment by tbee** [comment]
I assume you have found how to do it, but just in case some one has the same question: it is done through CSS: -fxx-arrow-position and -fxx-arrow-direction
