### ISSUE TITLE
CalendarTimeTextField drop with timeZone

### ISSUE THREAD

**Issue by VincentBonnafous** [JFXtras/jfxtras#16]
Hi,

Your lib is great, nice job

But, i create a CalendarTimtextField with a format and a timezone.

with this code : 

``` java
final CalendarTimeTextField lCalendarTimePicker = new CalendarTimeTextField();
SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
timeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
lCalendarTimePicker.setDateFormat(timeFormat);
```

and the drop combo don't display the first slider for the hours.

![datepickerdrop](https://cloud.githubusercontent.com/assets/9962744/5201910/646828aa-7578-11e4-912c-de6e37549688.png)

**Comment by VincentBonnafous** [comment]
I use 8.0-r3 version

**Comment by tbee** [comment]
I'll take a peek tonight, see what is causing this. No exceptions in the console?

Tom

**Comment by VincentBonnafous** [comment]
No message in the console

Thanks, here is the complete code to test quickly.

``` javascript
public class CalendarTimePickerSample1 extends Application {

    private Stage stage;

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        this.stage = stage;
        stage.setTitle("DatePickerSample ");
        initUI();
        stage.show();
    }

    private void initUI() {

        GridPane lGridPane = new GridPane();
        lGridPane.setVgap(10);

        Scene scene = new Scene(lGridPane, 400, 400);
        stage.setScene(scene);

        final CalendarTimeTextField lCalendarTimePicker = new CalendarTimeTextField();
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        timeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        lCalendarTimePicker.setDateFormat(timeFormat);

        lGridPane.add(lCalendarTimePicker, 0, 0, 2, 1);
    }
}

```

**Comment by tbee** [comment]
Well, that is interesting, setting a timezone in a totally none timezone string renderer. The time picker indeed was not handling it right, I fixed that I hope (please try r4-SNAPSHOT and reopen if I did not), but what is much more interesting is what you want to achieve with setting that timezone.

**Comment by VincentBonnafous** [comment]
OK(It works).
I work in the spatial domain for the CNES ( French Spatial Agence) and the people use dates in UTC

**Comment by tbee** [comment]
Ok, But it does not make any difference for the time picker what timezone it is in, it simply selects hours from 0 to 23 (or 0 AM to 11 PM). That is the same in any timezone, so setting the timezone has no value.

But it is good to hear that it is solved.
