### ISSUE TITLE
setTitleBarStyleClass does not work for me

### ISSUE THREAD

**Issue by dwaddell** [JFXtras/jfxtras#22]
When using setTitleBarStyleClass to "custom-window-titlebar" I will get "custom-window-titlebar" returned through getTitleBarStyleClass however the values I set in the class "custom-window-titlebar" are not being applied.  There is a real possibility that I am doing something incorrectly however I am having trouble finding examples using this online.

Window wTest = new Window("Insert title here!");
wTest.setTitleBarStyleClass("custom-window-titlebar");
apAnchor.getChildren().add(wTest );

/\* Trying to make things different, red */
.custom-window-titlebar {
    -fx-glass-color: rgba(255, 0, 0, 0.4);
    -fx-alignment: center;
    -fx-background-color: linear-gradient(to bottom, derive(-fx-glass-color, 30%), -fx-glass-color);
    -fx-border-color: derive(-fx-glass-color, -60%);
    -fx-border-width: 2;
    -fx-background-insets: 1;
    -fx-border-radius: 3;
    -fx-background-radius: 3;
    -fx-stroke: rgba(255,0,0,50);
    -fx-fill: rgba(255,0,0,50);
    }

Thanks,
Drew

**Comment by miho** [comment]
Which version do you use? Are you sure that you apply the CSS file?

**Comment by tbee** [comment]
Closed because of inactivity
