### ISSUE TITLE
Dragging is reversed when node orientation is RTL

### ISSUE THREAD

**Issue by vova1987** [JFXtras/jfxtras#31]
When dragging an appointment pane inside an Agenda control set with RTL orientation, the pane moves to the opposite side of the mouse.

**Comment by tbee** [comment]
Can you provide a small example? I have to confess that I have not ever run Agenda in RTL.

**Comment by vova1987** [comment]
Sure...
just set the nodeOrientation property of thhe agenda control to
RIGHT_TO_LEFT.
then add a new appointment and drag it to another day column.
You will see that the mouse and the pane are going to opposite directions...

**Comment by tbee** [comment]
Indeed. The cause seems to be that I do the drag calculations using screen based X and Y, which are (as it seems) not included in the automatic mirroring of the X. The screen is of course the thing that all nodes share, so it is easy. I have to think about how to fix this...
