### ISSUE TITLE
DisabledCalendar not working with LocalDateTextField

### ISSUE THREAD

**Issue by Maxoudela** [JFXtras/jfxtras#33]
Run this sample program that dynamically disabled all visible Calendars when a range is displayed : 

``` Java
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.util.Callback;

/**
 *
 * @author samir.hadzic
 */
public class Test extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        BorderPane pane = new BorderPane();
        LocalDateTextField field = new LocalDateTextField();
        field.setLocalDateRangeCallback(new Callback<LocalDatePicker.LocalDateRange, Void>() {

            @Override
            public Void call(LocalDatePicker.LocalDateRange param) {
                field.disabledLocalDates().clear();
                List<LocalDate> list = new ArrayList<>();
                for (LocalDate current = param.getStartLocalDate(); current.compareTo(param.getEndLocalDate()) <= 0; current = current.plusDays(1)) {
                    list.add(current);
                }
                field.disabledLocalDates().addAll(list);

                return null;
            }
        });
        pane.setCenter(field);

        Scene scene = new Scene(pane);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

}
```

The reason is that the LocalDateTextFieldSkin is syncing its disabledCalendars with the CalendarTextField. BUT there is not syncing between the CalendarTextField and the CalendarPicker displayed. The disabledCalendar are only added to CalendarPicker when the popup is shown. Therefore, if you add some disabledCalendars after the popup is shown, it will not be considered.

My advice would be to refactor all these classes in order to factorize all these properties in order to avoid syncing all List between each components. It will be simpler, faster and more efficient.

**Comment by tbee** [comment]
Good catch! Not sure what you mean with "factorize", but finding a better way of forwaring the lists is a good idea.

**Comment by Maxoudela** [comment]
Well I explained it a bit here : https://groups.google.com/d/msg/jfxtras-dev/5IIImyXEaO0/o5-yWf5VgKQJ

I wanted to create abstract class that have the common properties. But I don't know if this will resolve this issue.

Thing is I don't really like the idea of syncing three list together because that means adding listeners everywhere.. Proof is that we have issue with that..
I'll take a look tomorrow to see if I find an elegant solution.

**Comment by tbee** [comment]
I understand. Your approach will not solve the problem, because it uses the same concept as I did: each control has its own implementation (aka list) and the skin somehow must render that. If it chooses to do so by reusing another component (which is, after all, composition), then you'll end up syncing lists. 

I think the basic concept is ok, we need to find a better approach for the syncing.

**Comment by tbee** [comment]
Thinking a bit about it, but if I recall correctly the sync is done per change, which is not that bad: initialize once then keep in sync. It may not be pretty, but it may not be so bad either. Maybe just fixing the bug could be the best approach, but I have to look at the code first. I know it was put together under some time pressure.

**Comment by Maxoudela** [comment]
A solution would be to add a "syncCalendar" method in "DateTimeToCalendarHelper" (or elsewhere) and to sync the List in "setupPopup" of CalendarTextFieldSkin.

In fact the issue is not coming from the LocaleDateTextField but the CalendarTextField. Because the LocaleDateTextField is delegating everything to the CalendarTextField.

**Comment by tbee** [comment]
Yes, in order to only have to maintain one code base, the Calendar based controls are the actual controls being shown, the rest is just wrapping. Some day I'll move all the code to Java 8 datetime classes and reverse the dependency.

**Comment by Maxoudela** [comment]
Does the solution sounds good? I can make the PR right away.

**Comment by tbee** [comment]
I do not have eyes on the source, but a fill-initially-then-sync-changes seems like the way to go, yes.
And, ah, a test case should be present as well, because this is a behavior that is easily broken again. One could test if the correct button is disabled.

And how about the highlighed calendars, do they have the same issue? Probably.

**Comment by Maxoudela** [comment]
Yes of course I will add some test case when modifying in runtime some List.

Yes highlighted calendars have the same issue.
