### ISSUE TITLE
8.0-r4-SNAPSHOT in mavem ?

### ISSUE THREAD

**Issue by kaiocezar** [JFXtras/jfxtras#35]
when will be the release of the 8.0-r4-SNAPSHOT in mavem ?, because this simple example with this version

**Comment by tbee** [comment]
The nightly builds are present in sonatype's (maven's) snapshot repository. There is one made yesterday.
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/

**Comment by kaiocezar** [comment]
but as I lay in my pom.xml?
When I put
<dependency>
<groupId> org.jfxtras </ groupId>
<artifactId> jfxtras-book </ artifactId>
<version> 8.0-SNAPSHOT-r4 </ version>
</ dependency>
Gets error in pom

**Comment by tbee** [comment]
Have you tried leaving out all those spaces? And you might need to include the sonatype snapshot repository. Only Maven central is included by default.

http://stackoverflow.com/questions/16286055/how-to-get-snapshot-from-sonatype

**Comment by kaiocezar** [comment]
no, I'm using the mavem. I have to download the project or to use it in my pom.xml?

**Comment by tbee** [comment]
Use in in the pom
Include the sonatype snapshot repository

**Comment by kaiocezar** [comment]
Could you show me an example of pom.xml there because every time I put on 8.0-r4-SNAPSHOT is in error in my pom.

**Comment by tbee** [comment]
what is the error? Also include the full pom file.

**Comment by kaiocezar** [comment]
in eclips gets error saying when they think the repository; it just takes the version 8.0-r3, when I put the 8.0-r4-SNAPSHOT he can not find, please you have any examples of pom using the v4

**Comment by kaiocezar** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>Clinic</groupId>
    <artifactId>Clinic</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <directory>src</directory>
                <excludes>
                    <exclude>*_/_.java</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>

```
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>5.1.9</version>
    </dependency>

    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-core</artifactId>
        <version>4.2.19.Final</version>
    </dependency>

    <!-- for JPA, use hibernate-entitymanager instead of hibernate-core -->
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-entitymanager</artifactId>
        <version>4.2.19.Final</version>
    </dependency>
    <dependency>
        <groupId>np.com.ngopal</groupId>
        <artifactId>javafx-autocomplete-field</artifactId>
        <version>1.0.0</version>
    </dependency>

    <!-- for JFXtras - Agenda -->
    <dependency>
        <groupId>org.jfxtras</groupId>
        <artifactId>jfxtras-agenda</artifactId>
        <version>8.0-r3</version>
    </dependency>
    <dependency>
        <groupId>org.jfxtras</groupId>
        <artifactId>jfxtras-labs</artifactId>
        <version>8.0-r3</version>
    </dependency>

</dependencies>
```

</project>

**Comment by tbee** [comment]
That is because Maven central is included automatically while searching for jars, Sonatype's snaphot is not (snapshots are not allowed in maven central), that is what is missing.

http://stackoverflow.com/questions/16286055/how-to-get-snapshot-from-sonatype

**Comment by kaiocezar** [comment]
Thanks man it worked thank you for real, I have not seen so far an agenda API as good as this.

**Comment by stdex** [comment]
2 days I'm search problem (I use FXSampler, but in my code LocalDateTimeTextField look differ then in FXSampler, then I realized that I needed to update) ...

![image](https://cloud.githubusercontent.com/assets/4608879/9181929/58f16df8-3fb0-11e5-8a76-39fe995da677.png)

```
<repositories>
    <repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>

<dependencies>
    <dependency>
        <groupId>org.jfxtras</groupId>
        <artifactId>jfxtras-controls</artifactId>
        <version>8.0-r4-SNAPSHOT</version>
    </dependency>
</dependencies>
```

**Comment by tbee** [comment]
Beware: there were changes in JavaFX 8.20 that forces you the use of 8.0-R4-SNAPSHOT. I will release a R5 soon (when the memory issues have been solved in Agenda).
