### ISSUE TITLE
Needs a newer estable versión of jfxtras

### ISSUE THREAD

**Issue by javlaks** [JFXtras/jfxtras#36]
Well, this is not an issue, it is just more like a release of a new stable version that supports jdk 8u40.

I had updated all my old code to 8u40 but the release of jfxtras r3 from October of last year, has issues to display some controls.

Thanks a lot.

**Comment by miguelbaldi** [comment]
That's really annoying. We are using jdk 8u51 and LocalDateTimeTextField does not work, the styles got really messy and don't show the popup buttons. I've tested on 8.0-r4-SNAPSHOT and worked like a charm.

**Comment by Maxoudela** [comment]
I'm using the version from the current repo with 8u40 and I don't have any issue. What is the problem?

**Comment by javlaks** [comment]
My problem is using 8u40 or newer with jfxtras r3 o less. With r4-snapshot i do not have issues. All works fine. The main problem is the "snapshot" word. Do not represent "stable".

So, if you could release the r4 as stable would be great. (I can delete the word "snapshot" word from the jar file, but it doesn't the case, you understand! )

**Comment by tbee** [comment]
THere is a memory issue in Agenda, I'm going to look into that when I return from vacation next week and then create a proper release.

**Comment by javlaks** [comment]
Hey Tom, thank you so much! For you and your team! :P

**Comment by tbee** [comment]
8.0-r4 is on its way to maven central
