### ISSUE TITLE
CalendarTimePicker has transparent background

### ISSUE THREAD

**Issue by aalmiray** [JFXtras/jfxtras#39]
With jfxtras-8.0-r3 & JDK8u60 on OSX and Windows. See linked screenshot. Usage is via FXML with no additional settings

```
<LocalDateTimeTextField fx:id="roundStartTime" style="-fx-background-color: white;" GridPane.columnIndex="1" GridPane.columnSpan="2" GridPane.rowIndex="4" />
```

Tried to find some way to tweak the background color using CSS to no avail. Any clues on how to fix this?

![jfxtras](http://www.jroller.com/aalmiray/resource/jfxtras-localdatetimetextfield.png)

**Comment by tbee** [comment]
There were changes in JavaFX in how CSS is handled in controls, would you mind first upgrading to R4 or R5-snapshot?

**Comment by aalmiray** [comment]
I can confirm that upgrading to 8.0-r4 solves the problem.
