### ISSUE TITLE
CheckComboBox Does Not Appear to Load FXML data as Expected

### ISSUE THREAD

**Issue by b-mag** [JFXtras/jfxtras#43]
If you populate a CheckComboBox with sample data in FXML as you would a ComboBox it treats it as a single item. 

```
                    <CheckComboBox fx:id="checkComboBoxRepeatDays" prefHeight="25.0" prefWidth="158.0" >
                        <items>
                            <FXCollections fx:factory="observableArrayList">
                                <String fx:value="All" />
                                <String fx:value="Sunday" />
                                <String fx:value="Monday" />
                                <String fx:value="Tuesday" />
                                <String fx:value="Wednesday" />
                                <String fx:value="Thursday" />
                                <String fx:value="Friday" />
                                <String fx:value="Saturday" />
                            </FXCollections>
                        </items> 
                    </CheckComboBox>
```

![checkcombobox](https://cloud.githubusercontent.com/assets/15198259/11006410/ab2cac9c-8491-11e5-8a85-8999f7787927.png)

A quick switch to combo box object yields the expected result:

![combobox](https://cloud.githubusercontent.com/assets/15198259/11006483/0196108c-8492-11e5-9fbf-fefc3587dda3.png)

**Comment by tbee** [comment]
Aren't you mixing up projects? I do not know of a CheckCombobox in JFXtras. There is one in ControlsFX

http://controlsfx.bitbucket.org/org/controlsfx/control/CheckComboBox.html
