### ISSUE TITLE
ActionsCallback not called when  setAllowDragging is false

### ISSUE THREAD

**Issue by AlexRoig** [JFXtras/jfxtras#48]
I want to create a calendar just to display some information, which shouldn't be modificable by the user. So I disabled the resize and the drag features. I find no way to trigger the ActionsCallback when double-clicking an event.

``` java
agenda.setAllowDragging(false);
agenda.setActionCallback((Agenda.Appointment myAppointment) -> {
    System.err.println("This is never shown");
    return null;
});
```

**Comment by tbee** [comment]
I do not quite understand the issue. The problem is that if the dragging is disabled, the action callback is not triggered. Correct?

**Comment by AlexRoig** [comment]
Yes. Provably it's expected behavior, but in my opinion, disabling the dragging, shouldn't exclude this event from  being triggered.
I couldn't find on the API any other way to trigger an action when clicking or double-clicking an appointment.

**Comment by tbee** [comment]
I agree. I'll look into it, probably tomorrow

**Comment by tbee** [comment]
This is not the cause; I have dragging disabled and can still double click to trigger the action callback.

**Comment by tbee** [comment]
I've added allow resize and dragging to Agenda's sample (in JFXtrasSamples see jfxtras.org) so you can check it for yourself.
