### ISSUE TITLE
Can't include in Project

### ISSUE THREAD

**Issue by Juliang0705** [JFXtras/jfxtras#64]
I'm trying to link to the project with gradle, like below. However, I get this error
``
- What went wrong:
  Could not resolve all dependencies for configuration ':compileClasspath'.
  > Could not find org.jfxtras:jfxtras-agenda:8.0-r1-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/jfxtras-agenda-8.0-r1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/jfxtras-agenda-8.0-r1-SNAPSHOT.jar
      file:/Users/Juliang/.m2/repository/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/maven-metadata.xml
      file:/Users/Juliang/.m2/repository/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/jfxtras-agenda-8.0-r1-SNAPSHOT.pom
      file:/Users/Juliang/.m2/repository/org/jfxtras/jfxtras-agenda/8.0-r1-SNAPSHOT/jfxtras-agenda-8.0-r1-SNAPSHOT.jar
  Required by:
      :CoursePicker:unspecified`
  ``
  Is it the way I am importing it or am I missing something?

dependencies {
    compile files('src/jsoup-1.8.3.jar')
    compile files('src/pdfbox-app-2.0.0-RC2.jar')
    compile (group: 'org.jfxtras', name: 'jfxtras-agenda', version: '8.0-r1-SNAPSHOT')
}

**Comment by tbee** [comment]
I need to see the repositories that you are including. The snapshots are hosted in [Sonatype's](https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/) , as described on [JFXtras.org](http://jfxtras.org/), and you need to add that to the build.gradle.

But, ah, we're already at 8.0-r5-SNAPSHOT

**Comment by tbee** [comment]
closed because of no response
