### ISSUE TITLE
jfxtras-labs-samples-8.0-r6-SNAPSHOT-shadow.jar download

### ISSUE THREAD

**Issue by Kaito23** [JFXtras/jfxtras#66]
Hey,

where to download the
jfxtras-labs-samples-8.0-r6-SNAPSHOT-shadow.jar?
The link on your side is broken :)

Greetings 
Kaito

**Comment by tbee** [comment]
Apparently I have not pushed r6-SNAPSHOT to sonatype yet, R5-SNAPSHOT will be fine.

https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-labs-samples/

**Comment by tbee** [comment]
closed because of no response

**Comment by Kaito23** [comment]
it is working now, but it does not work. Throws many errors:

ERROR: Initial filename: bsh/BSHTryStatement.class
ERROR: Class name: bsh.BSHThrowStatement
ERROR: Initial filename: bsh/BSHThrowStatement.class
ERROR: Class name: bsh.BSHTernaryExpression
ERROR: Initial filename: bsh/BSHTernaryExpression.class
ERROR: Class name: bsh.BSHSwitchStatement
ERROR: Initial filename: bsh/BSHSwitchStatement.class
ERROR: Class name: bsh.BSHSwitchLabel
ERROR: Initial filename: bsh/BSHSwitchLabel.class
ERROR: Class name: bsh.BSHStatementExpressionList

**Comment by tbee** [comment]
Those messages are most not related to JFXtras but the EDI/editor (jedit) you are using.
https://github.com/romuloceccon/jedit/blob/master/org/gjt/sp/jedit/bsh/BSHStatementExpressionList.java

**Comment by Kaito23** [comment]
Found a solution using another java jre version :) thanks great work!
