### ISSUE TITLE
Graphical tests fail on Linux

### ISSUE THREAD

**Issue by daviddbal** [JFXtras/jfxtras#68]
There are the errors from building.  Done on the last shadow commit you made in July.:
david@david-desktop:~/Documents/temp/jfxtras$ gradle build
:jfxtras-common:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-common:compileRetrolambdaMain
:jfxtras-common:processResources UP-TO-DATE
:jfxtras-common:classes
:jfxtras-common:jar
:jfxtras-fxml:compileJava
Note: /home/david/Documents/temp/jfxtras/jfxtras-fxml/src/main/java/jfxtras/fxml/JFXtrasBuilderFactory.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-fxml:compileRetrolambdaMain
:jfxtras-fxml:processResources UP-TO-DATE
:jfxtras-fxml:classes
:jfxtras-fxml:jar
:jfxtras-controls:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-controls:compileRetrolambdaMain
:jfxtras-controls:processResources
:jfxtras-controls:classes
:jfxtras-controls:jar
:jfxtras-agenda:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-agenda:compileRetrolambdaMain
:jfxtras-agenda:processResources
:jfxtras-agenda:classes
:jfxtras-agenda:jar
:jfxtras-font-roboto:compileJava
:jfxtras-font-roboto:compileRetrolambdaMain
:jfxtras-font-roboto:processResources
:jfxtras-font-roboto:classes
:jfxtras-font-roboto:jar
:jfxtras-gauge-linear:compileJava
Note: /home/david/Documents/temp/jfxtras/jfxtras-gauge-linear/src/main/java/jfxtras/internal/scene/control/gauge/linear/skin/AbstractLinearGaugeSkin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-gauge-linear:compileRetrolambdaMain
:jfxtras-gauge-linear:processResources
:jfxtras-gauge-linear:classes
:jfxtras-gauge-linear:jar
:jfxtras-menu:compileJava
:jfxtras-menu:compileRetrolambdaMain
:jfxtras-menu:processResources UP-TO-DATE
:jfxtras-menu:classes
:jfxtras-menu:jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:signArchives SKIPPED
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:jfxtras-common:javadoc
javadoc: warning - --base-dir must be present for includes or file reference features to work properly.
WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/util/NodeUtil.java:213: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/util/NodeUtil.java:224: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/util/NodeUtil.java:254: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/util/NodeUtil.java:267: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GridPane.java:106: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GridPane.java:117: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GridPane.java:128: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GridPane.java:139: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/HBox.java:134: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/VBox.java:134: warning - @return tag has no arguments.
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GenericLayoutConstraints.java:92: warning: no description for @param
         \* @param node
           ^
/home/david/Documents/temp/jfxtras/jfxtras-common/src/main/java/jfxtras/scene/layout/GenericLayoutConstraints.java:73: warning: no description for @param
         \* @param node
           ^
13 warnings
:jfxtras-fxml:javadoc
javadoc: warning - --base-dir must be present for includes or file reference features to work properly.
WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
1 warning
:jfxtras-controls:javadoc
javadoc: warning - --base-dir must be present for includes or file reference features to work properly.
WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
1 warning
:jfxtras-agenda:javadoc
javadoc: warning - --base-dir must be present for includes or file reference features to work properly.
WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
/home/david/Documents/temp/jfxtras/jfxtras-agenda/src/main/java/jfxtras/scene/control/agenda/Agenda.java:542: warning - Tag @see: can't find setAppointmentGroup(AppointmentGroup) in jfxtras.scene.control.agenda.Agenda.AppointmentImplBase
/home/david/Documents/temp/jfxtras/jfxtras-agenda/src/main/java/jfxtras/scene/control/agenda/Agenda.java:542: warning - Tag @see: can't find setAppointmentGroup(AppointmentGroup) in jfxtras.scene.control.agenda.Agenda.AppointmentImplBase
3 warnings
:jfxtras-agenda:docJar
:jfxtras-agenda:sourcesJar
:jfxtras-agenda:signArchives SKIPPED
:jfxtras-agenda:assemble
:jfxtras-test-support:compileJava
Note: /home/david/Documents/temp/jfxtras/jfxtras-test-support/src/main/java/jfxtras/test/TestUtil.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:jfxtras-test-support:compileRetrolambdaMain
:jfxtras-test-support:processResources UP-TO-DATE
:jfxtras-test-support:classes
:jfxtras-test-support:jar
:jfxtras-agenda:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:jfxtras-agenda:compileRetrolambdaTest
:jfxtras-agenda:processTestResources
:jfxtras-agenda:testClasses
:jfxtras-agenda:test

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularSpanningAppointment                                                                          FAILED
    java.lang.AssertionError at AgendaRenderTest.java:301

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderOverlappingAppointments                                                                             FAILED
    java.lang.AssertionError at AgendaRenderTest.java:361

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointmentLocalDate                                                                        FAILED
    java.lang.AssertionError at AgendaRenderTest.java:195

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentOffset                                                                            FAILED
    java.lang.AssertionError at AgendaRenderTest.java:232

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderTwoConsequetiveRegularAppointment                                                                   FAILED
    java.lang.AssertionError at AgendaRenderTest.java:110

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointment FAILED
    java.lang.AssertionError at AgendaRenderTest.java:86

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentCalendar                                                                          FAILED
    java.lang.AssertionError at AgendaRenderTest.java:157

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointment FAILED
    java.lang.AssertionError at AgendaRenderTest.java:329

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointmentHijrahDate                                                                       FAILED
    java.lang.AssertionError at AgendaRenderTest.java:214

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentDaySkin                                                                           FAILED
    java.lang.AssertionError at AgendaRenderTest.java:279

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentZoned                                                                             FAILED
    java.lang.AssertionError at AgendaRenderTest.java:177

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentInstant                                                                           FAILED
    java.lang.AssertionError at AgendaRenderTest.java:258

jfxtras.scene.control.agenda.test.AgendaMenuTest > toggleWholedayInMenu FAILED
    java.lang.AssertionError at AgendaMenuTest.java:161

55 tests completed, 13 failed
:jfxtras-agenda:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':jfxtras-agenda:test'.
  
  > There were failing tests. See the report at: file:///home/david/Documents/temp/jfxtras/jfxtras-agenda/build/reports/tests/index.html
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 52.28 secs

**Comment by tbee** [comment]
I cannot do much without the actual problems. What is failing?

**Comment by daviddbal** [comment]
I sent you the log of the failed tests.  Could this have something to do with the font problem that you fixed with the Robo font?  The following tests are failing:

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularSpanningAppointment FAILED
java.lang.AssertionError at AgendaRenderTest.java:301

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderOverlappingAppointments FAILED
java.lang.AssertionError at AgendaRenderTest.java:361

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointmentLocalDate FAILED
java.lang.AssertionError at AgendaRenderTest.java:195

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentOffset FAILED
java.lang.AssertionError at AgendaRenderTest.java:232

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderTwoConsequetiveRegularAppointment FAILED
java.lang.AssertionError at AgendaRenderTest.java:110

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointment FAILED
java.lang.AssertionError at AgendaRenderTest.java:86

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentCalendar FAILED
java.lang.AssertionError at AgendaRenderTest.java:157

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointment FAILED
java.lang.AssertionError at AgendaRenderTest.java:329

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderWholeDayAppointmentHijrahDate FAILED
java.lang.AssertionError at AgendaRenderTest.java:214

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentDaySkin FAILED
java.lang.AssertionError at AgendaRenderTest.java:279

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentZoned FAILED
java.lang.AssertionError at AgendaRenderTest.java:177

jfxtras.scene.control.agenda.test.AgendaRenderTest > renderRegularAppointmentInstant FAILED
java.lang.AssertionError at AgendaRenderTest.java:258

jfxtras.scene.control.agenda.test.AgendaMenuTest > toggleWholedayInMenu FAILED
java.lang.AssertionError at AgendaMenuTest.java:161

**Comment by tbee** [comment]
Are you sure you send those? I'm not finding any email in my mailbox. Maybe resend?

**Comment by tbee** [comment]
The build is reworked to Maven under Ubuntu. Everything compiles and all test are green at this time.
