### ISSUE TITLE
Compile error on icalendaragenda on Linux.

### ISSUE THREAD

**Issue by daviddbal** [JFXtras/jfxtras#69]
Compile error on icalendaragenda on linux.  The errors involve generics being typed only to Object.  Oddly, these errors are not found on Jenkins or Windows builds.  Also, if same code is put inside the icalendarfx package it compiles.  Errors don't exist in Eclipse either (on Linux).  This evidence suggests Gradle isn't property connecting the iCalendarFx dependency for iCalendarAgenda.

Something wrong with build.gradle?

david@david-desktop:~/workspace/jfxtras$ gradle :jfxtras-icalendaragenda:build
:jfxtras-common:compileJava UP-TO-DATE
:jfxtras-common:compileRetrolambdaMain UP-TO-DATE
:jfxtras-common:processResources UP-TO-DATE
:jfxtras-common:classes UP-TO-DATE
:jfxtras-common:jar UP-TO-DATE
:jfxtras-fxml:compileJava UP-TO-DATE
:jfxtras-fxml:compileRetrolambdaMain UP-TO-DATE
:jfxtras-fxml:processResources UP-TO-DATE
:jfxtras-fxml:classes UP-TO-DATE
:jfxtras-fxml:jar UP-TO-DATE
:jfxtras-controls:compileJava UP-TO-DATE
:jfxtras-controls:compileRetrolambdaMain UP-TO-DATE
:jfxtras-controls:processResources UP-TO-DATE
:jfxtras-controls:classes UP-TO-DATE
:jfxtras-controls:jar UP-TO-DATE
:jfxtras-agenda:compileJava UP-TO-DATE
:jfxtras-agenda:compileRetrolambdaMain UP-TO-DATE
:jfxtras-agenda:processResources UP-TO-DATE
:jfxtras-agenda:classes UP-TO-DATE
:jfxtras-agenda:jar UP-TO-DATE
:jfxtras-common:javadoc UP-TO-DATE
:jfxtras-fxml:javadoc UP-TO-DATE
:jfxtras-controls:javadoc UP-TO-DATE
:jfxtras-agenda:javadoc UP-TO-DATE
:jfxtras-icalendarfx:compileJava UP-TO-DATE
:jfxtras-icalendarfx:compileRetrolambdaMain UP-TO-DATE
:jfxtras-icalendarfx:processResources UP-TO-DATE
:jfxtras-icalendarfx:classes UP-TO-DATE
:jfxtras-icalendarfx:jar UP-TO-DATE
:jfxtras-icalendaragenda:compileJava UP-TO-DATE
:jfxtras-icalendaragenda:compileRetrolambdaMain UP-TO-DATE
:jfxtras-icalendaragenda:processResources UP-TO-DATE
:jfxtras-icalendaragenda:classes UP-TO-DATE
:jfxtras-icalendarfx:javadoc UP-TO-DATE
:jfxtras-icalendaragenda:javadoc UP-TO-DATE
:jfxtras-icalendaragenda:docJar UP-TO-DATE
:jfxtras-icalendaragenda:jar UP-TO-DATE
:jfxtras-icalendaragenda:sourcesJar UP-TO-DATE
:jfxtras-icalendaragenda:signArchives SKIPPED
:jfxtras-icalendaragenda:assemble UP-TO-DATE
:jfxtras-test-support:compileJava UP-TO-DATE
:jfxtras-test-support:compileRetrolambdaMain UP-TO-DATE
:jfxtras-test-support:processResources UP-TO-DATE
:jfxtras-test-support:classes UP-TO-DATE
:jfxtras-test-support:jar UP-TO-DATE
:jfxtras-icalendaragenda:compileTestJava
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:167: error: cannot find symbol
                .withSummary("new summary")
                ^
  symbol:   method withSummary(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:288: error: cannot find symbol
                .withSequence(1);
                ^
  symbol:   method withSequence(int)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:340: error: cannot find symbol
                .withRecurrenceRule("FREQ=MONTHLY;BYDAY=3SU")
                ^
  symbol:   method withRecurrenceRule(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:379: error: cannot find symbol
                .withSequence(1);
                ^
  symbol:   method withSequence(int)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:495: error: cannot find symbol
                .withDateTimeStamp("20150110T080000Z")
                ^
  symbol:   method withDateTimeStamp(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/PopupReviseAllTest.java:547: error: incompatible types: Object cannot be converted to VEvent
                .withRecurrenceRule(new RecurrenceRule2()
                                   ^
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/VJournalMakeiTIPTest.java:42: error: cannot find symbol
                .withDateTimeStamp("20160518T232502Z")
                ^
  symbol:   method withDateTimeStamp(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/internal/scene/control/skin/agenda/icalendar/base24hour/popup/VTodoMakeiTIPTest.java:43: error: cannot find symbol
                .withSummary("test todo")
                ^
  symbol:   method withSummary(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:34: error: cannot find symbol
                .withUniqueIdentifier("20151109T082900-001@jfxtras.org")
                ^
  symbol:   method withUniqueIdentifier(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:47: error: incompatible types: Object cannot be converted to VEvent
                .withRecurrenceRule(new RecurrenceRule2()
                                   ^
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:57: error: cannot find symbol
                .withUniqueIdentifier("20150110T080000-002@jfxtras.org")
                ^
  symbol:   method withUniqueIdentifier(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:70: error: incompatible types: Object cannot be converted to VEvent
                .withRecurrenceRule(new RecurrenceRule2()
                                   ^
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:80: error: cannot find symbol
                .withDescription("Weekly1 Description")
                ^
  symbol:   method withDescription(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:96: error: cannot find symbol
                .withUniqueIdentifier("20150110T080000-002@jfxtras.org")
                ^
  symbol:   method withUniqueIdentifier(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:117: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 11, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:135: error: cannot find symbol
                .withDescription("Daily1 Description")
                ^
  symbol:   method withDescription(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:152: error: cannot find symbol
                .withDescription("Daily2 Description")
                ^
  symbol:   method withDescription(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:170: error: cannot find symbol
                .withDescription("Daily6 Description")
                ^
  symbol:   method withDescription(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:187: error: cannot find symbol
                .withDescription("Individual Description")
                ^
  symbol:   method withDescription(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:201: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:212: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:235: error: cannot find symbol
                .withDateTimeStart(LocalDate.of(2015, 11, 8))
                ^
  symbol:   method withDateTimeStart(LocalDate)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:251: error: cannot find symbol
                .withDateTimeStart(LocalDate.of(2015, 11, 8))
                ^
  symbol:   method withDateTimeStart(LocalDate)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/ICalendarStaticComponents.java:266: error: cannot find symbol
                .withDateTimeStart(LocalDate.of(2015, 11, 8))
                ^
  symbol:   method withDateTimeStart(LocalDate)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/deletor/DeleteOneTest.java:74: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/deletor/DeleteAllTest.java:75: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseThisAndFutureTest.java:119: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseThisAndFutureTest.java:203: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2015, 12, 25, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseThisAndFutureTest.java:212: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseAllTest.java:236: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseAllTest.java:244: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 19, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseAllTest.java:329: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 17, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/editors/revisor/ReviseAllTest.java:337: error: cannot find symbol
                .withRecurrenceId(LocalDateTime.of(2016, 5, 19, 10, 0))
                ^
  symbol:   method withRecurrenceId(LocalDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/RenderVEventsTest.java:231: error: cannot find symbol
                .withDateTimeStamp(LocalDateTime.now().atZone(ZoneId.of("Z")))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/MakeNewVEventsTest.java:47: error: cannot find symbol
                .withCategories("group10")
                ^
  symbol:   method withCategories(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/MakeNewVEventsTest.java:102: error: cannot find symbol
                .withCategories("group00")
                ^
  symbol:   method withCategories(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/MakeNewVEventsTest.java:133: error: cannot find symbol
                .withCategories("group00")
                ^
  symbol:   method withCategories(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/MakeNewVEventsTest.java:167: error: cannot find symbol
                .withCategories("group00")
                ^
  symbol:   method withCategories(String)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/GraphicallyChangeTest.java:112: error: cannot find symbol
                .withDateTimeStamp(new DateTimeStamp(editedVEvent1.getDateTimeStamp())) // copy DTSTAMP, because it depends on current date/time
                ^
  symbol:   method withDateTimeStamp(DateTimeStamp)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/GraphicallyChangeTest.java:165: error: cannot find symbol
                .withSequence(1);
                ^
  symbol:   method withSequence(int)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/GraphicallyChangeTest.java:213: error: cannot find symbol
                .withSequence(1);
                ^
  symbol:   method withSequence(int)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/GraphicallyChangeTest.java:221: error: cannot find symbol
                .withDateTimeStamp(new DateTimeStamp(editedVEvent1.getDateTimeStamp())) // copy DTSTAMP, because it depends on current date/time
                ^
  symbol:   method withDateTimeStamp(DateTimeStamp)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/agenda/RevisePopupTest.java:71: error: cannot find symbol
                .withDateTimeStamp(new DateTimeStamp(vComponentIndividual.getDateTimeStamp()))
                ^
  symbol:   method withDateTimeStamp(DateTimeStamp)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/misc/MakeAppointmentsTest.java:84: error: cannot find symbol
              .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 11, 10, 8, 0), ZoneOffset.UTC))
              ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/misc/MakeAppointmentsTest.java:128: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/DemoTest.java:25: error: no suitable method found for add(Object)
            agenda.getVCalendar().getVEvents().add(ICalendarStaticComponents.getDaily1()
                                              ^
    method Collection.add(VEvent) is not applicable
      (argument mismatch; Object cannot be converted to VEvent)
    method List.add(VEvent) is not applicable
      (argument mismatch; Object cannot be converted to VEvent)
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:124: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 11, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:136: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 11, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:151: error: cannot find symbol
            .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 11, 10, 8, 0), ZoneOffset.UTC))
            ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:166: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:180: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:193: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
/home/david/workspace/jfxtras/jfxtras-icalendaragenda/src/test/java/jfxtras/scene/control/agenda/icalendar/trial/controller/CalendarController.java:208: error: cannot find symbol
                .withDateTimeStamp(ZonedDateTime.of(LocalDateTime.of(2015, 1, 10, 8, 0), ZoneOffset.UTC))
                ^
  symbol:   method withDateTimeStamp(ZonedDateTime)
  location: class Object
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
53 errors
:jfxtras-icalendaragenda:compileTestJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':jfxtras-icalendaragenda:compileTestJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.217 secs

**Comment by tbee** [comment]
Is this still an issue?

**Comment by daviddbal** [comment]
Yes.

**Comment by daviddbal** [comment]
I have no clue why the problem occurs.  I could remove all the uses of chaining to eliminate the problem, but that would be tedious and seems unnecessary.  Any thoughts?

**Comment by tbee** [comment]
I've just done a full compile of jfxtras under Debian and there are no errors except some javadoc warnings. So the problem must be in your setup. Have you tried a clean before assembling? Because the missing "with" seems to indicate you are using an older version of a jar where the withers are not present.

**Comment by daviddbal** [comment]
Thanks for running the test.  

I don't know what could be wrong with my setup.  I have tried in on two different machines.  One had a fresh install of Ubuntu 16.04 and, a fresh clone of jfxtras, the latest Java JDK.  I got the same errors.  I am running Ubuntu 16.04 on both machines.  The Gradle I'm using is old, version 2.1 (the default installed in Ubuntu).  Could that be a problem?

I'll try it again just in case I missed something.

The really weird thing is the errors didn't exist when the project was on jfxtras-labs.  Once I moved it the errors appeared.

**Comment by tbee** [comment]
If you use ./gradlew clean assemble in the root of jfxtras, it should build using the appropriate gradle. You may need to +x gradlew.

**Comment by daviddbal** [comment]
I did the following:
./gradlew clean
./gradlew :jfxtras-icalendaragenda:build

I still got the errors on the "with" methods.

**Comment by daviddbal** [comment]
I even upgraded to Gradle 3.2.1, still has errors.

**Comment by daviddbal** [comment]
I found a forum post about a similar issue.  The issue went unsolved.  Here is the post:
[https://github.com/mkarneim/pojobuilder/issues/86](url)

**Comment by tbee** [comment]
That apparently is lombok related; lombok is a code generation tool. It is not strange it does not generate certain methods. Our situation has hardcoded methods.

**Comment by tbee** [comment]
Now I have them. What happens if you just run "./gradlew build" on the toplevel?

Jenkins runs on Debian and it compiles completely as well.
http://jenkins.softworks.nl:8082/job/JFXtras8.0NightlyBuild/920/consoleFull

**Comment by tbee** [comment]
I don't know. The VEvent class is compiled, but somehow the test source code does not see the withDateTimeStamp. They are public... Drawing a blank.

**Comment by tbee** [comment]
Building has been reworked to use Maven. All compile and all test run, so please try this again (if it is still valid).
