### ISSUE TITLE
allow constrained date ranges on date/time pickers

### ISSUE THREAD

**Issue by millmanorama** [JFXtras/jfxtras#7]
It would be great if there was a way to constrain the available date/times to a within a range, so the user could not pick a date/time outside that range.

**Comment by tbee** [comment]
CalendarPicker has a disabledCalendars property. You can register a callback in the calendarRangeCallbackProperty and set the disabledCalendars accordingly.

**Comment by millmanorama** [comment]
that you for the quick reply.  I am using a LocalDateTimeTextField, is
there a corresponding feature for it?

On Mon, May 5, 2014 at 11:29 AM, Tom Eugelink notifications@github.comwrote:

> CalendarPicker has a disabledCalendars property. You can register a
> callback in the calendarRangeCallbackProperty and set the disabledCalendars
> accordingly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JFXtras/jfxtras/issues/7#issuecomment-42200261
> .

## 

Jonathan Millman
www.jmillman.com

**Comment by tbee** [comment]
There should be (because I reuse CalendarPicker everywhere) but I see the property is not forwarded. So that would need a small extension.

**Comment by tbee** [comment]
I've created a first implementation and it works. But because it's JFXtras and not JFXtras-labs I need to roll it out to all components (Calendar, LocalDate, LocalDateTime) with tests and samples. It will take some more work.

**Comment by tbee** [comment]
The latest 8.0-r2-SNAPSHOT should have the code now

**Comment by millmanorama** [comment]
thanks, for working on this so quickly.  I will take look soon.

**Comment by millmanorama** [comment]
I see the callback, but I am a little confused about what to do with it.  Could you post a short example?

**Comment by tbee** [comment]
Upon a range change, you can modify the disabled calendar/date property to hold the appropriate values for the active range.

Tom

**Comment by millmanorama** [comment]
This does not seem like a viable way to achieve my goal of not allowing selection outside a range.  If I have to add every possible disabled LocalDateTime to a list i will have to generate thousands and thousands of them, one for every possible time (at least to the minute...).  It seems better to provide a validation callback and test potential LocalDateTimes as needed.

**Comment by tbee** [comment]
Hmmm, disabled date does not work on time level.

How do you see that? While dragging the slider you cannot skip values. So once a value is selected, it gets validated and if disapproved the old value is set?

Tom

**Comment by millmanorama** [comment]
yes. or in my use case, since validation is simply 'is it within valid range?', the end point of the range could be selected.

**Comment by tbee** [comment]
I'll give it some thought. I see some problems but maybe that is just me :-)

**Comment by millmanorama** [comment]
well, you know much more about how these controls work, And I mostly just care about my use case ;)

Thanks for all your help.

PS.  If it makes it any easier (it might make it harder!), What I REALLY want is to not even show the date/times out side the range, so for example if the range was march 2000 - jan 2001, the user would never even be able to show the date/times in feb 2000

**Comment by tbee** [comment]
Well, that all is not that hard to add, it seems, at least on day level. And sounds like a fair use case. The advantage of open source is that I can switch much quicker than the official controls ;-)

Tom

**Comment by tbee** [comment]
Ok. I've added a valueValidationCallback to the Calendar versions of the pickers. Not the textfield or the JSR-310 versions. Can you give them a test before I roll this out further (that is always a lot of repetitive work)?

**Comment by tbee** [comment]
No feedback in a long time. Closing.
