### ISSUE TITLE
CalendarTimePicker no hour step function

### ISSUE THREAD

**Issue by MakerTim** [JFXtras/jfxtras#70]
There is a secondStepProperty and minuteStepProperty inside CalendarTimePicker
but there is no such thing for hours...

Is it intentional missing? or just a oversight

because there is now for me no way to change the step of the hour slider

**Comment by tbee** [comment]
Oversight. I simply did not think that anyone would step hours not by 1. But apparently you do :-)

**Comment by MakerTim** [comment]
Well, the odd thing is,
that the default is 10 instead of 1... thats the reason why i want to change it 😕

**Comment by tbee** [comment]
Which is weird. Only the minute and second scroll sliders are getting a block increment value.
https://github.com/JFXtras/jfxtras/blob/8.0/jfxtras-controls/src/main/java/jfxtras/internal/scene/control/skin/CalendarTimePickerSkin.java#L95

Can you create a simple example to reproduce this?

**Comment by MakerTim** [comment]
https://gist.github.com/MakerTim/f9fa39608a23d195d6105ca8039bfb71

I tried to make an example, but its not consistent if it happens or not

im on Java 1.8.0_91, windows 10  i come across many bugs in javafx, so it can be a bug on there side to

Here a screencapture of it happening
minutes are working fine, but seconds not that great
https://puu.sh/s4yBr.mp4

**Comment by tbee** [comment]
Hm. That is always a challenge. I'll revisit the code this weekend.
As a side note; did you come to my talk on the JFall yesterday?

**Comment by MakerTim** [comment]
No i had school, and for this year, my school doesn't support JFall yet
so i could not come this year :(

**Comment by tbee** [comment]
Hm. I saw it in the samples as well. I'm not doing anything with the block step of the hour slider, so I have to assume this is some kind of default behavior of the slider. Anyhow, I've added an hourStepSize default set to 1 and it seems to have solved the issue. Get the latest r6-snapshot to test.

**Comment by MakerTim** [comment]
Awesome work :D
