### ISSUE TITLE
Popup not showing properly

### ISSUE THREAD

**Issue by Maxoudela** [JFXtras/jfxtras#71]
Hi guys,

I have an issue with the LocalDateTextField (and others that uses the Textfield).

Basically, I'm adding the LocalDateTextField into a cell of a SpreadsheetView (of ControlsFX - like a TableView). And I want to show directly the popup. But since the TextField has not been shown somehow, its height is not set. 
Therefore the code in CalendarTextFieldSkin : 
`popup.show(textField, NodeUtil.screenX(getSkinnable()), NodeUtil.screenY(getSkinnable()) + textField.getHeight());`

is wrong and the popup is shown above the TextField.

I don't have a sample test case to reproduce it unfortunately. My solution consists of preventing that case by looking to the real height if necessary like that : 
`double height = textField.getHeight() == 0.0 ? textField.prefHeight(-1): textField.getHeight();`

I can provide a pull request if you want.

**Comment by tbee** [comment]
Thanks for reporting. Please do!

**Comment by Maxoudela** [comment]
Do I need to add a test?

I don't really know how to reproduce that, it's a bit of a timing issue I guess..

**Comment by tbee** [comment]
I would not know how to reproduce that either, so skip the test.

**Comment by Maxoudela** [comment]
Resolved by pull request #72
