### ISSUE TITLE
TextField tooltip cannot be removed

### ISSUE THREAD

**Issue by Maxoudela** [JFXtras/jfxtras#79]
Hi,

In the code, we currently have that : 
```
if (getSkinnable().getTooltip() == null)
		{
			// TODO: internationalize the tooltip
			getSkinnable().setTooltip(new Tooltip("Type a date or use # for today, or +/-<number>[d|w|m|y] for delta's (for example: -3m for minus 3 months)\nUse cursor up and down plus optional shift (week), ctrl (month) or alt (year) for quick keyboard changes."));
		}
```

I want to display a CalendarTextField where no tooltip is displayed on the TextField. Currently, if I do not set any tooltip, the one above will be set. If I set an empty Tooltip, an empty tooltip will be shown..

We should find a way to allow the user to completely remove the tooltip if he wants to. Currently I do not see a clear solution..

**Comment by tbee** [comment]
I'm not sure where this code is (man you're doing a lot :-) ), but if it were to be set in the constructor as the default text, then it can be overridden as needed.

**Comment by Maxoudela** [comment]
It's situated in the createNodes method of the CalendarTextFieldSkin.

It's in the constructor of the CalendarTextFieldSKin so I don't see how I could override that..?

I'm going through an intense session of Calendar tweak, thus all the enhancements^^

**Comment by tbee** [comment]
So if it is in the createNodes, then it will only be executed upon construction and you should be able to overwrite once the control is created?

**Comment by Maxoudela** [comment]
Yes indeed you're right! I don't know why I haven't seen that solution before.. 
Thanks, we can close ;)

**Comment by Maxoudela** [comment]
Also on a side note, we have a ColumnConstraints in CalendarTextFieldSKin defined that way : 
`ColumnConstraints column0 = new ColumnConstraints(100, 10, Double.MAX_VALUE);`

Which means we want a minimum width of 100 and a prefWidth of 10... Shouldn't the two values be reversed?

**Comment by tbee** [comment]
minimum width of 10 is also weird, so 100,100,max seems more logical?

**Comment by Maxoudela** [comment]
Well I have the case where I do put the CalendarTextField in very tiny space. 10 is a bit extreme but 100 minimum is too much IMHO. 
I know that it's weird not to display all the date in the TextField, but it's much more weird when the CalendarTextField is going of bounds because the space you want it to be is to tight. In that situation, we can't even see what we're typing..

**Comment by tbee** [comment]
Then I'll say: make it so :-)

**Comment by Maxoudela** [comment]
Allright it's included in the Pull request :)

**Comment by tbee** [comment]
I've added some additional checking on if parse errors are thrown correctly. I hated the stack traces in the console.
