### ISSUE TITLE
Window - apply default JavaFX Stylesheets

### ISSUE THREAD

**Issue by jhulick** [JFXtras/jfxtras#84]
I'm finding it difficult to apply default JavaFX (Modena, Caspian) styles to the themable Window component. Is there a simply way to do this through the Window API, or by extension? I would prefer not to build out my own styles from scratch. Thanks in advance.

**Comment by tbee** [comment]
I'm not sure the original author is still providing support. I've asked him.

**Comment by miho** [comment]
The window component was optimized for custom styles. Currently, there's no direct way to accomplish that. You have to define a custom style. But in your CSS you can derive colors etc. from Modena/Caspian.

**Comment by tbee** [comment]
Closed due to inactivity
