### ISSUE TITLE
Change height of hour in agenda

### ISSUE THREAD

**Issue by BjornWater** [JFXtras/jfxtras#85]
Is there a possibility to change the height of an hour in the agenda controls?

**Comment by tbee** [comment]
The minimal height of an hour relates to the text size: 2* text height + 10px for margin
https://github.com/JFXtras/jfxtras/blob/8.0/jfxtras-agenda/src/main/java/jfxtras/internal/scene/control/skin/agenda/base24hour/AgendaSkinTimeScale24HourAbstract.java#L589

But if there is more room, than all the available room is distributed equally. So yes it is possible, but probably not how you thought it would go. The fact is that the hour size is roughly the (total size - header)  / 24.

The text size is determined from CSS.
https://github.com/JFXtras/jfxtras/blob/8.0/jfxtras-agenda/src/main/java/jfxtras/internal/scene/control/skin/agenda/base24hour/LayoutHelp.java#L82

**Comment by BjornWater** [comment]
What css property should it be then. Can only find that the height is determined by the bounds in parents. But you cannot change that height in css

**Comment by tbee** [comment]
You cannot set the hour height, it is the available height divided by 24. But with a minimum.

**Comment by tbee** [comment]
Closed due to inactivity
