### ISSUE TITLE
Disable date time editing in text field 

### ISSUE THREAD

**Issue by zahid-ali-shah** [JFXtras/jfxtras#90]
I want to disable date time editing in text field so that i can only select datetime from calendar popup. How can I do this?

**Comment by tbee** [comment]
Good question. I never though about that. I will take a peek this weekend.

**Comment by tbee** [comment]
OK. So I've added a enabled property, which was still missing, but it behaves identical to what is on a textfield: user can select the text, but not change it (so popup is not working in that mode). I'm having a bit of a problem convicing myself that what you want is a normal operating mode and should be supported by the control. Maybe you can convince me ;-) Why do you want only entries through the popup?

You can of course do this yourself with a TextField, image button and the normal date picker in  popup. But I understand that it is a lot of work which the textfield does for you.

**Comment by MahmoudMabrok** [comment]
Please ,Could you close this issue to stop other solve it ?
