### ISSUE TITLE
CalendarPicker: cannot set properties in FXML

### ISSUE THREAD

**Issue by bendardenne** [JFXtras/jfxtras#91]
Hi,

I have the following FXML:

```FXML
<?import javafx.scene.layout.AnchorPane?>
<?import jfxtras.scene.control.CalendarPicker?>
<AnchorPane xmlns:fx="http://javafx.com/fxml">
  <CalendarPicker locale="de"/>
</AnchorPane>
```

As in CalendarPickerFXMLTest.  But I am getting "Unable to coerce" exceptions.  
I am using 8.0-r5.

This is not such a big deal as I can set the locale in code, but still, I assume it should work, shouldn't it?

**Comment by tbee** [comment]
Yes. Especially since there is a test covering that. Interesting.

**Comment by bendardenne** [comment]
Okay, my mistake, seems like I need to use a JFXtrasBuilderFactory with FXMLLoader. Closing the issue.

**Comment by tbee** [comment]
Yes, somewhere the code for adding the builders to the FXMLoader needs to be added. Good that you found that yourself.
