### ISSUE TITLE
How to Use JFxtras with netbeans and scenebuilder?

### ISSUE THREAD

**Issue by ayushchadha23** [JFXtras/jfxtras#99]

**Comment by tbee** [comment]
The problem with scenebuilder is that it cannot use control jars which require more than one jar (like JFXtras has a controls, and common, and agenda, etc). So when using SceneBuilder include the all jar

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jfxtras-all%22

**Comment by ayushchadha23** [comment]
When I downloaded the jars and imported them to scenebuilder and netbeans and it worked thanks!

**Comment by AdemYoussef** [comment]
Hi Sir @ayushchadha23 
I m a newbie to scenebuilder and JavaFX , all I know is how to configure scenebuilder on Netbeans to use it hehe XD
I m working on a school project and I liked the very useful controls that JFxtrats offers and I want to use them 
but I have no idea how to even import or install or whatever ... to make JFxtras working on my ide ( Netbeans 8.2 ) 
can you please help me? 
will be very appreciated
